name: testing1

on:
  issue_comment:
    types: [created] # triggers on adding a comment
  pull_request:
    types: [opened, edited, synchronize] 

jobs:
  testing2:
    runs-on: ubuntu-latest
    permissions:
     checks: write
    steps:
      - name: testing3
        run: |
          REPO=${{ github.repository }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          SHORTCUT_BOT_USERNAME="BHYub" 
          
          # Get the correct PR number and SHA
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            PR_NUMBER=${{ github.event.issue.number }}
            PR_SHA=$(curl -s -H "Authorization: token $TOKEN" \
              "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER" | jq -r .head.sha)
          else
            PR_NUMBER=${{ github.event.pull_request.number }}
            PR_SHA=${{ github.event.pull_request.head.sha }}
          fi

          echo "Using PR SHA: $PR_SHA"

          COMMENTS=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments")

          if echo "$COMMENTS" | jq -e ".[] | select(.user.login == \"$SHORTCUT_BOT_USERNAME\") | select(.body | contains(\"This pull request has been linked to\"))" > /dev/null; then
            echo "Valid Shortcut link found."
           curl -X POST \
              -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/check-runs \
              -d '{
                "name": "testing2",
                "head_sha": "'"$PR_SHA"'",
                "status": "completed",
                "conclusion": "success"
              }'
          else
            echo "This PR does not have a linked Shortcut story."
            exit 1
          fi
