
name: Block Merge Without Shortcut Link tests

on:
  issue_comment:
    types: [created] #triggers on adding a comment
  pull_request:
    types: [opened, edited, synchronize] 
  pull_request_review:  
    types: [submitted]   #triggers on review and approval 
jobs:
  check-shortcut-link:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
     
      - name: Check for Shortcut link in pull request
      
        run: |
         
          PR_NUMBER=${{ github.event.issue.number }}
          
          
          REPO=${{ github.repository }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          SHORTCUT_BOT_USERNAME="BHYub" 
          COMMENTS=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments")
            
          echo $COMMENTS  
          
          if echo "$COMMENTS" | jq -e ".[] | select(.user.login == \"$SHORTCUT_BOT_USERNAME\") | select(.body | contains(\"This pull request has been linked to\"))" > /dev/null; then
            echo "Valid Shortcut link found."
          else
            echo "This PR does not have a linked Shortcut story."
            exit 1
          fi
  
