name: Block Merge Without Shortcut Link

on:
  pull_request_review:
    types: [submitted]

jobs:
  check-shortcut-link:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Shortcut link
        run: |
          # Env variables 
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          SHORTCUT_BOT_USERNAME="BHYub"
          
          # get comments of PR
          COMMENTS=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments")

          # Shortcut bot comment verification
          if ! echo "$COMMENTS" | grep -q "\"user\": {\"login\": \"$SHORTCUT_BOT_USERNAME\".*\"body\":.*This pull request has been linked to"; then
            echo "This PR does not have a linked Shortcut story."
            exit 1
          fi
