name: Block Merge Without Shortcut Link tests

on:
  issue_comment:
    types: [created] # triggers on adding a comment
  pull_request:
    types: [opened, edited, synchronize] 

jobs:
  check-shortcut-link:
    runs-on: ubuntu-latest
    permissions:
     checks: write
    steps:
      - name: Check for Shortcut link in comment or PR
        run: |
          REPO=${{ github.repository }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          SHORTCUT_BOT_USERNAME="BHYub" 
          
          # Get the correct PR number and SHA
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            PR_NUMBER=${{ github.event.issue.number }}
          else
            PR_NUMBER=${{ github.event.pull_request.number }}
          fi

          # Get the SHA for the current PR
          PR_SHA=${{ github.event.pull_request.head.sha }}

          COMMENTS=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments")

          if echo "$COMMENTS" | jq -e ".[] | select(.user.login == \"$SHORTCUT_BOT_USERNAME\") | select(.body | contains(\"This pull request has been linked to\"))" > /dev/null; then
            echo "Valid Shortcut link found."
            # Update the check run with the correct SHA
            curl -X POST \
              -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/check-runs \
              -d '{
                "name": "Shortcut Link Check",
                "head_sha": "'"$PR_SHA"'",
                "status": "completed",
                "conclusion": "success"
              }'
          else
            echo "This PR does not have a linked Shortcut story."
            exit 1
          fi
