name: Check PR Linked to Shortcut

# Déclenchement de l'action sur les événements pull_request et issue_comment
on:
  pull_request:
    types: [opened, edited, synchronize]
  issue_comment:
    types: [created]

jobs:
  check-shortcut:
    # S'assure que c'est bien une PR dans le cas d'un commentaire
    if: github.event.issue.pull_request != null || github.event.pull_request != null
    runs-on: ubuntu-latest

    steps:
      # Step 1: Vérifier si la PR a un commentaire du bot
      - name: Check if PR is linked to a Shortcut story
        run: |
          # Cas où c'est une Pull Request (ouverture, modification, etc.)
          PR_NUMBER=$(echo "${{ github.event.pull_request.number || github.event.issue.number }}")

          # Utilisation de l'API GitHub pour récupérer tous les commentaires de la PR
          COMMENTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments")

          # Vérifier si un commentaire du bot shortcut-integration[bot] existe
          if echo "$COMMENTS" | grep -q '"user": {"login": "BHYub"}' && echo "$COMMENTS" | grep -q "this PR is linked"; then
            echo "PR is linked to a Shortcut story."
          else
            echo "PR is not linked to a Shortcut story. Please link this PR to a story."
            exit 1  # Fail the action si la PR n'est pas liée
          fi
