name: Block Merge Without Shortcut Link

on:
  pull_request:
    types: [opened, edited, synchronize]  # Déclenchement lors de la création, modification ou synchronisation de la PR
  pull_request_review:
    types: [submitted]  # Déclenchement lors de l'approbation de la PR
  issue_comment:
    types: [created]    # Déclenchement lors de l'ajout d'un commentaire

jobs:
  check-shortcut-link:
    runs-on: ubuntu-latest
    steps:

      - name: Check for Shortcut link
        run: |
          # Variables d'environnement
          if github.event_name == 'issue_comment'
          PR_NUMBER=${{ github.event.issue.number }}
          else
          PR_NUMBER=${{ github.event.pull_request.number }}
          fi
          REPO=${{ github.repository }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          SHORTCUT_BOT_USERNAME="BHYub"  # Remplacez par le nom d'utilisateur exact du bot

          # Récupérer les commentaires de la PR
          COMMENTS=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments")

          # Vérifier si le commentaire du bot est présent
          if echo "$COMMENTS" | jq -e ".[] | select(.user.login == \"$SHORTCUT_BOT_USERNAME\") | select(.body | contains(\"This pull request has been linked to\"))" > /dev/null; then
            echo "Valid Shortcut link found."
          else
            echo "This PR does not have a linked Shortcut story."
            exit 1
          fi
